spring:
  application:
    name: eureka-server 

server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  
    
ribbon:
   eureka:
      enabled: false
